version: "3"
services:
  next:
    build:
      context: ./next
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: next-container
    volumes:
      - ./next:/usr/src/app/next
    command: npm run dev